language: ruby
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
script: 'bundle exec rake'
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - ruby-head

gemfile:
  - test/gemfiles/Gemfile.rails-4.0.x
  - test/gemfiles/Gemfile.rails-4.1.x
  - test/gemfiles/Gemfile.rails-4.2.x
  - test/gemfiles/Gemfile.rails-5.0.x
  - test/gemfiles/Gemfile.rails-5.1.x
  - test/gemfiles/Gemfile.rails-5.2.x
  - test/gemfiles/Gemfile.rails-6.0.x

matrix:
  exclude:
    - rvm: ruby-head
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
    - rvm: ruby-head
      gemfile: test/gemfiles/Gemfile.rails-4.1.x
  allow_failures:
    - rvm: ruby-head
